ktor:
  deployment:
    port: 8080
  application:
    modules:
      - com.appsandgames34.ApplicationKt.module

postgres:
  url: "jdbc:postgresql://localhost:5432/edificio34"
  user: "postgres"
  password: "1234"
